# Generated by Django 5.0.4 on 2024-04-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('video_title', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('emotional_tone', models.CharField(max_length=100)),
                ('engagement_score', models.FloatField()),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
    ]
